# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
permalink: /:year/:month/:title
title: Brock Boland
email: brock@brockboland.com
description: >
  My name is Brock. I’m an iOS developer in Seattle, and no longer brew beer as often as I used to, even though it’s obligatory once your beard gets as long as mine has.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brockboland.com" # the base hostname & protocol for your site
twitter_username: brock
github_username:  brockboland

# Build settings
markdown: kramdown

exclude: [".*", "post_template.md", "README.md"]
